# Generated by Django 5.2.9 on 2026-01-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
