# Generated by Django 5.2.9 on 2026-01-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0003_userfollows_is_blocked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
