# Generated by Django 5.2.9 on 2026-01-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0005_userfollows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollows',
            name='is_blocked',
        ),
    ]
