# Generated by Django 5.2.9 on 2025-12-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('subscriber', 'Abonné')], default='subscriber', max_length=50, verbose_name='Rôle'),
        ),
    ]
